spring:
  application:
    name: text-library-service
  data:
    mongodb:
      host: text_db
      #      port: [port]
      #      username: [username]
      #      password: [password]
      database: text_library
  jackson:
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
opentracing:
  jaeger:
    log-spans: false
    udp-sender:
      host: jaeger-agent
