version: '3.2'

services:
  novel-ai:
    image: novel-ai:latest
    networks:
      - app
      - tracing
    ports:
      - 9080:8080
      - 6005:5005

  author-service:
    image: author-service:latest
    networks:
      - app
      - tracing
    ports:
      - 9081:8080
      - 6015:5005

  text-library-service:
    image: text-library-service:latest
    networks:
      - app
      - database
      - tracing
    ports:
      - 9082:8080
      - 6025:5005

  novel-library-service:
    image: novel-library-service:latest
    networks:
      - app
      - database
      - tracing
    ports:
      - 9083:8080
      - 6035:5005

  library_db:
    image: postgres:alpine
    networks:
      - database
    ports:
      - 5432:5432
    volumes:
      - library_db_data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_PASSWORD: library
      POSTGRES_DB: library
      POSTGRES_USER: library
      PGDATA: /var/lib/postgresql/data/pg_data

  text_db:
    image: mongo:latest
    networks:
      - database
    environment:
      - MONGO_DATA_DIR=/data/db
#    volumes:
#      - text_db_data:/data/db
#      - text_db_config:/data/configdb
    ports:
      - 27017:27017

  text_db-seed:
    build: ./text_db-seed
    networks:
      - database

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
    networks:
      - tracing
#    ports:
#      - "14269"
#      - "14268:14268"
#      - "14267"
#      - "14250"
#      - "9411:9411"
    restart: on-failure
    depends_on:
      - cassandra-schema

  jaeger-query:
    image: jaegertracing/jaeger-query
    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
    networks:
      - tracing
    ports:
      - "16686:16686"
#      - "16687"
    restart: on-failure
    depends_on:
      - cassandra-schema

  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
    networks:
      - tracing
    ports:
#      - "5775:5775/udp"
      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
    restart: on-failure
    depends_on:
      - jaeger-collector

  jaeger-spark-dependencies:
    image: jaegertracing/spark-dependencies
    networks:
      - tracing
    restart: on-failure
    environment:
      - STORAGE=cassandra
      - CASSANDRA_CONTACT_POINTS=cassandra
    depends_on:
      - jaeger-collector

  cassandra:
    image: cassandra:3.9
    networks:
      - tracing
    volumes:
      - cassandra_db_data:/var/lib/cassandra

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema
    networks:
      - tracing
    depends_on:
      - cassandra

networks:
  app:
  database:
  tracing:

volumes:
  library_db_data:
#  text_db_data:
#  text_db_config:
  cassandra_db_data:
