opentracing:
  jaeger:
    enabled: false
novelai:
  author-service:
    base-uri: http://localhost:10081
  text-library-service:
    base-uri: http://localhost:10082
  novel-library-service:
    base-uri: http://localhost:10083
