spring:
  application:
    name: author-service
  jackson:
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
opentracing:
  jaeger:
    log-spans: false
    udp-sender:
      host: jaeger-agent
author:
  content:
    num-paragraphs: 20
  text-library-service:
    base-uri: http://text-library-service:8080
logging:
  level:
    de.roamingthings: DEBUG
management:
  endpoint:
    health:
      show-components: always
