spring:
  application:
    name: novel-ai-service
  jackson:
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
opentracing:
  jaeger:
    log-spans: true
    udp-sender:
      host: jaeger-agent
novelai:
  author-service:
    base-uri: http://author-service:8080
  text-library-service:
    base-uri: http://text-library-service:8080
  novel-library-service:
    base-uri: http://novel-library-service:8080
  document-generator-service:
    base-uri: http://document-generator-service:8080
logging:
  level:
    de.roamingthings: DEBUG
management:
  endpoint:
    health:
      show-components: always
