opentracing:
  jaeger:
    udp-sender:
      host: localhost
novelai:
  author-service:
    base-uri: http://localhost:9081
  text-library-service:
    base-uri: http://localhost:9082
  novel-library-service:
    base-uri: http://localhost:9083
  document-generator-service:
    base-uri: http://localhost:9084
