spring:
  application:
    name: novel-ai-service
  jackson:
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
opentracing:
  jaeger:
    log-spans: true
    udp-sender:
      host: jaeger-agent
