server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: library
    password: library
  opentracing:
    jaeger:
      udp-sender:
        host: localhost
